steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gmail-processor', '.']
    env:
      - 'NODE_ENV=production'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gmail-processor']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'michelle-gmail'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gmail-processor'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'GMAIL_CLIENT_ID=GMAIL_CLIENT_ID:latest,GMAIL_CLIENT_SECRET=GMAIL_CLIENT_SECRET:latest,GMAIL_REFRESH_TOKEN=GMAIL_REFRESH_TOKEN:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,SHEETS_ID_MICHELLE_CHAT_LOG=SHEETS_ID_MICHELLE_CHAT_LOG:latest,SHARED_SECRET=SHARED_SECRET:latest'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,PUBSUB_TOPIC=gmail-notifications-michelle,PUBSUB_SUBSCRIPTION=projects/$PROJECT_ID/subscriptions/gmail-notifications-sub-michelle,GMAIL_USER_EMAIL=info@appraisily.com,NODE_ENV=production'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'
      - '--cpu-throttling'
      - '--service-account'
      - '$PROJECT_ID-compute@developer.gserviceaccount.com'

  # Create Cloud Scheduler job for Gmail watch renewal
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - 'gmail-watch-renewal'
      - '--schedule=0 */6 * * *'
      - '--uri=https://michelle-gmail-856401495068.us-central1.run.app/api/gmail/renew-watch'
      - '--http-method=POST'
      - '--attempt-deadline=300s'
      - '--time-zone=UTC'
      - '--description=Renews Gmail watch every 6 hours to ensure continuous email processing'
      - '--headers=Authorization=Bearer ${SHARED_SECRET}'
    allowFailure: true  # In case the job already exists

  # Create Cloud Scheduler job for health check
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - 'gmail-service-health'
      - '--schedule=*/15 * * * *'
      - '--uri=https://michelle-gmail-856401495068.us-central1.run.app/health'
      - '--http-method=GET'
      - '--attempt-deadline=30s'
      - '--time-zone=UTC'
      - '--description=Health check every 15 minutes to keep service warm'
    allowFailure: true  # In case the job already exists

images:
  - 'gcr.io/$PROJECT_ID/gmail-processor'

options:
  logging: CLOUD_LOGGING_ONLY